# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'comment_utiliser.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1017, 427)
        MainWindow.setWindowTitle("Enigma How to use it ?")
        MainWindow.setStyleSheet("background-color: #0D1B2B ;")
        MainWindow.setFixedSize(1017, 427)

        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(410, 10, 191, 31))
        self.label.setAutoFillBackground(False)
        self.label.setStyleSheet("background-color: rgb(28, 38, 61);\n"
"font: 10pt \"MS Shell Dlg 2\";\n"
"color: rgb(255, 255, 255);\n"
"")
        self.label.setAlignment(QtCore.Qt.AlignCenter)
        self.label.setObjectName("label")
        self.label_3 = QtWidgets.QLabel(self.centralwidget)
        self.label_3.setGeometry(QtCore.QRect(60, 50, 201, 31))
        self.label_3.setAutoFillBackground(False)
        self.label_3.setStyleSheet("background-color: rgb(28, 38, 61);\n"
"color: rgb(255, 255, 255);\n"
"")
        self.label_3.setAlignment(QtCore.Qt.AlignCenter)
        self.label_3.setObjectName("label_3")
        self.label_4 = QtWidgets.QLabel(self.centralwidget)
        self.label_4.setGeometry(QtCore.QRect(750, 50, 201, 31))
        self.label_4.setAutoFillBackground(False)
        self.label_4.setStyleSheet("background-color: rgb(28, 38, 61);\n"
"font: 9pt \"MS Shell Dlg 2\";\n"
"color: rgb(255, 255, 255);\n"
"")
        self.label_4.setAlignment(QtCore.Qt.AlignCenter)
        self.label_4.setObjectName("label_4")
        self.label_5 = QtWidgets.QLabel(self.centralwidget)
        self.label_5.setGeometry(QtCore.QRect(60, 100, 371, 51))
        self.label_5.setAutoFillBackground(False)
        self.label_5.setStyleSheet("background-color: rgb(28, 38, 61);\n"
"font: 7pt \"MS Shell Dlg 2\";\n"
"color: rgb(255, 255, 255);\n"
"")
        self.label_5.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.label_5.setWordWrap(True)
        self.label_5.setObjectName("label_5")
        self.label_6 = QtWidgets.QLabel(self.centralwidget)
        self.label_6.setGeometry(QtCore.QRect(60, 170, 121, 31))
        self.label_6.setAutoFillBackground(False)
        self.label_6.setStyleSheet("background-color: rgb(28, 38, 61);\n"
"color: rgb(255, 255, 255);\n"
"")
        self.label_6.setAlignment(QtCore.Qt.AlignCenter)
        self.label_6.setObjectName("label_6")
        self.label_8 = QtWidgets.QLabel(self.centralwidget)
        self.label_8.setGeometry(QtCore.QRect(60, 220, 121, 31))
        self.label_8.setAutoFillBackground(False)
        self.label_8.setStyleSheet("background-color: rgb(28, 38, 61);\n"
"color: rgb(255, 255, 255);\n"
"")
        self.label_8.setAlignment(QtCore.Qt.AlignCenter)
        self.label_8.setObjectName("label_8")
        self.label_9 = QtWidgets.QLabel(self.centralwidget)
        self.label_9.setGeometry(QtCore.QRect(60, 270, 121, 31))
        self.label_9.setAutoFillBackground(False)
        self.label_9.setStyleSheet("background-color: rgb(28, 38, 61);\n"
"color: rgb(255, 255, 255);\n"
"")
        self.label_9.setAlignment(QtCore.Qt.AlignCenter)
        self.label_9.setObjectName("label_9")
        self.label_10 = QtWidgets.QLabel(self.centralwidget)
        self.label_10.setGeometry(QtCore.QRect(60, 320, 121, 31))
        self.label_10.setAutoFillBackground(False)
        self.label_10.setStyleSheet("background-color: rgb(28, 38, 61);\n"
"color: rgb(255, 255, 255);\n"
"")
        self.label_10.setAlignment(QtCore.Qt.AlignCenter)
        self.label_10.setObjectName("label_10")
        self.label_11 = QtWidgets.QLabel(self.centralwidget)
        self.label_11.setGeometry(QtCore.QRect(200, 170, 231, 31))
        self.label_11.setAutoFillBackground(False)
        self.label_11.setStyleSheet("background-color: rgb(28, 38, 61);\n"
"font: 7pt \"MS Shell Dlg 2\";\n"
"color: rgb(255, 255, 255);\n"
"")
        self.label_11.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.label_11.setWordWrap(True)
        self.label_11.setObjectName("label_11")
        self.label_12 = QtWidgets.QLabel(self.centralwidget)
        self.label_12.setGeometry(QtCore.QRect(200, 220, 231, 31))
        self.label_12.setAutoFillBackground(False)
        self.label_12.setStyleSheet("background-color: rgb(28, 38, 61);\n"
"font: 7pt \"MS Shell Dlg 2\";\n"
"color: rgb(255, 255, 255);\n"
"")
        self.label_12.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.label_12.setWordWrap(True)
        self.label_12.setObjectName("label_12")
        self.label_13 = QtWidgets.QLabel(self.centralwidget)
        self.label_13.setGeometry(QtCore.QRect(200, 320, 231, 31))
        self.label_13.setAutoFillBackground(False)
        self.label_13.setStyleSheet("background-color: rgb(28, 38, 61);\n"
"font: 7pt \"MS Shell Dlg 2\";\n"
"color: rgb(255, 255, 255);\n"
"")
        self.label_13.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.label_13.setWordWrap(True)
        self.label_13.setObjectName("label_13")
        self.label_14 = QtWidgets.QLabel(self.centralwidget)
        self.label_14.setGeometry(QtCore.QRect(200, 270, 231, 31))
        self.label_14.setAutoFillBackground(False)
        self.label_14.setStyleSheet("background-color: rgb(28, 38, 61);\n"
"font: 7pt \"MS Shell Dlg 2\";\n"
"color: rgb(255, 255, 255);\n"
"")
        self.label_14.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.label_14.setWordWrap(True)
        self.label_14.setObjectName("label_14")
        self.label_7 = QtWidgets.QLabel(self.centralwidget)
        self.label_7.setGeometry(QtCore.QRect(580, 100, 371, 51))
        self.label_7.setAutoFillBackground(False)
        self.label_7.setStyleSheet("background-color: rgb(28, 38, 61);\n"
"font: 7pt \"MS Shell Dlg 2\";\n"
"color: rgb(255, 255, 255);\n"
"")
        self.label_7.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.label_7.setWordWrap(True)
        self.label_7.setObjectName("label_7")
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_2.setGeometry(QtCore.QRect(550, 170, 421, 221))
        self.label_2.setStyleSheet("background-color: rgb(28, 38, 61);")
        self.label_2.setText("")
        self.label_2.setPixmap(QtGui.QPixmap("img/how_to_use_enigmachine.png"))
        self.label_2.setScaledContents(True)
        self.label_2.setObjectName("label_2")
        self.label_15 = QtWidgets.QLabel(self.centralwidget)
        self.label_15.setGeometry(QtCore.QRect(200, 370, 231, 31))
        self.label_15.setAutoFillBackground(False)
        self.label_15.setStyleSheet("background-color: rgb(28, 38, 61);\n"
"font: 7pt \"MS Shell Dlg 2\";\n"
"color: rgb(255, 255, 255);\n"
"")
        self.label_15.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.label_15.setWordWrap(True)
        self.label_15.setObjectName("label_15")
        self.label_16 = QtWidgets.QLabel(self.centralwidget)
        self.label_16.setGeometry(QtCore.QRect(60, 370, 121, 31))
        self.label_16.setAutoFillBackground(False)
        self.label_16.setStyleSheet("background-color: rgb(28, 38, 61);\n"
"color: rgb(255, 255, 255);\n"
"")
        self.label_16.setAlignment(QtCore.Qt.AlignCenter)
        self.label_16.setObjectName("label_16")
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.label.setText(_translate("MainWindow", "  Comment utiliser enigma ?"))
        self.label_3.setText(_translate("MainWindow", "Configuration initiale "))
        self.label_4.setText(_translate("MainWindow", "Tuto image"))
        self.label_5.setText(_translate("MainWindow", "Avant d\'envoyer ou de décrypter un message, l\'opérateur doit configurer la machine selon un livret de codes secret partagé entre l\'expéditeur et le destinataire"))
        self.label_6.setText(_translate("MainWindow", "Positions rotors"))
        self.label_8.setText(_translate("MainWindow", "Anneaux de réglages"))
        self.label_9.setText(_translate("MainWindow", "Positions initiales"))
        self.label_10.setText(_translate("MainWindow", "Plugboard"))
        self.label_11.setText(_translate("MainWindow", "Choisir et placer les rotors dans un ordre précis"))
        self.label_12.setText(_translate("MainWindow", "Ajuster l\'offset de chaque rotor"))
        self.label_13.setText(_translate("MainWindow", "Relier les câbles. Attention a bien écrire en majuscule"))
        self.label_14.setText(_translate("MainWindow", "Régler les rotors sur une position de départ"))
        self.label_7.setText(_translate("MainWindow", "Dans l\'ordre encadré en rouge, de haut en bas : PlugBoard, Rotors, Anneaux de réglages, Positions initiales, Réflecteur et Clavier"))
        self.label_15.setText(_translate("MainWindow", "Reflecteur"))
        self.label_16.setText(_translate("MainWindow", "Reflecteur"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
