# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'true_main_interface.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1210, 628)
        MainWindow.setFixedSize(1210, 628)
        MainWindow.setStyleSheet("background-color: #0D1B2B ;")
        MainWindow.setWindowTitle("Enigma Machine")
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.QLabel_Logo = QtWidgets.QLabel(self.centralwidget)
        self.QLabel_Logo.setGeometry(QtCore.QRect(70, 10, 241, 131))
        self.QLabel_Logo.setText("")
        self.QLabel_Logo.setPixmap(QtGui.QPixmap("img/s-1.jpg"))
        self.QLabel_Logo.setScaledContents(True)
        self.QLabel_Logo.setObjectName("QLabel_Logo")
        self.pushButton = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton.setGeometry(QtCore.QRect(60, 150, 121, 23))
        self.pushButton.setStyleSheet("QPushButton{\n"
"border: 1px solid rgb(28, 38, 61);\n"
"color: black;\n"
"background-color: white;\n"
"border-radius: 5px;\n"
"}\n"
"\n"
"QPushButton:Hover{\n"
"border: 3px solid white;\n"
"color: white;\n"
"background-color:  rgb(28, 38, 61);\n"
"border-radius: 20px;\n"
"}")
        self.pushButton.setObjectName("pushButton")
        self.pushButton_2 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_2.setGeometry(QtCore.QRect(200, 150, 121, 23))
        self.pushButton_2.setStyleSheet("QPushButton{\n"
"border: 1px solid rgb(28, 38, 61);\n"
"color: black;\n"
"background-color: white;\n"
"border-radius: 5px;\n"
"}\n"
"\n"
"QPushButton:Hover{\n"
"border: 3px solid white;\n"
"color: white;\n"
"background-color:  rgb(28, 38, 61);\n"
"border-radius: 20px;\n"
"}background-color: rgb(255, 255, 255);")
        self.pushButton_2.setObjectName("pushButton_2")
        self.frame = QtWidgets.QFrame(self.centralwidget)
        self.frame.setGeometry(QtCore.QRect(60, 200, 261, 181))
        self.frame.setStyleSheet("background-color: rgb(28, 38, 61);\n"
"font: 7pt \"MS Shell Dlg 2\";\n"
"color: rgb(255, 255, 255);\n"
"")
        self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")

        self.jack_1 = QtWidgets.QLineEdit(self.frame)
        self.jack_1.setAlignment(QtCore.Qt.AlignCenter)
        self.jack_1.setGeometry(QtCore.QRect(10, 70, 61, 22))
        self.jack_1.setStyleSheet("background-color: rgb(199, 199, 199); color: black;")
        self.jack_1.setObjectName("jack_1")

        self.jack_2 = QtWidgets.QLineEdit(self.frame)
        self.jack_2.setAlignment(QtCore.Qt.AlignCenter)
        self.jack_2.setGeometry(QtCore.QRect(100, 70, 61, 22))
        self.jack_2.setStyleSheet("background-color: rgb(199, 199, 199); color: black;")
        self.jack_2.setObjectName("jack_2")

        self.jack_3 = QtWidgets.QLineEdit(self.frame)
        self.jack_3.setAlignment(QtCore.Qt.AlignCenter)
        self.jack_3.setGeometry(QtCore.QRect(190, 70, 61, 22))
        self.jack_3.setStyleSheet("background-color: rgb(199, 199, 199); color: black;")
        self.jack_3.setObjectName("jack_3")

        self.jack_1.setText("A")
        self.jack_2.setText("A")
        self.jack_3.setText("A")

        self.label_53 = QtWidgets.QLabel(self.frame)
        self.label_53.setGeometry(QtCore.QRect(10, 40, 21, 21))
        self.label_53.setAlignment(QtCore.Qt.AlignCenter)
        self.label_53.setObjectName("label_53")

        self.label_54 = QtWidgets.QLabel(self.frame)
        self.label_54.setGeometry(QtCore.QRect(100, 40, 21, 21))
        self.label_54.setAlignment(QtCore.Qt.AlignCenter)
        self.label_54.setObjectName("label_54")
        self.label_55 = QtWidgets.QLabel(self.frame)
        self.label_55.setGeometry(QtCore.QRect(190, 40, 21, 21))
        self.label_55.setAlignment(QtCore.Qt.AlignCenter)
        self.label_55.setObjectName("label_55")
        self.pushButton_3 = QtWidgets.QPushButton(self.frame)
        self.pushButton_3.setGeometry(QtCore.QRect(30, 40, 41, 23))
        self.pushButton_3.setObjectName("pushButton_3")
        self.pushButton_4 = QtWidgets.QPushButton(self.frame)
        self.pushButton_4.setGeometry(QtCore.QRect(120, 40, 41, 23))
        self.pushButton_4.setObjectName("pushButton_4")
        self.pushButton_5 = QtWidgets.QPushButton(self.frame)
        self.pushButton_5.setGeometry(QtCore.QRect(210, 40, 41, 23))
        self.pushButton_5.setObjectName("pushButton_5")
        self.pushButton_6 = QtWidgets.QPushButton(self.frame)
        self.pushButton_6.setGeometry(QtCore.QRect(140, 140, 41, 23))
        self.pushButton_6.setObjectName("pushButton_6")
        self.label_57 = QtWidgets.QLabel(self.frame)
        self.label_57.setGeometry(QtCore.QRect(60, 141, 61, 20))
        self.label_57.setAlignment(QtCore.Qt.AlignCenter)
        self.label_57.setObjectName("label_57")
        self.QLabel_Sortie_2 = QtWidgets.QLabel(self.frame)
        self.QLabel_Sortie_2.setGeometry(QtCore.QRect(40, 100, 161, 41))
        self.QLabel_Sortie_2.setStyleSheet("background-color: rgb(28, 38, 61);\n"
"font: 10pt \"MS Shell Dlg 2\";\n"
"color: rgb(255, 255, 255);\n"
"")
        self.QLabel_Sortie_2.setAlignment(QtCore.Qt.AlignCenter)
        self.QLabel_Sortie_2.setObjectName("QLabel_Sortie_2")
        self.QLabel_Sortie_3 = QtWidgets.QLabel(self.frame)
        self.QLabel_Sortie_3.setGeometry(QtCore.QRect(50, 0, 161, 41))
        self.QLabel_Sortie_3.setStyleSheet("background-color: rgb(28, 38, 61);\n"
"font: 10pt \"MS Shell Dlg 2\";\n"
"color: rgb(255, 255, 255);\n"
"")
        self.QLabel_Sortie_3.setAlignment(QtCore.Qt.AlignCenter)
        self.QLabel_Sortie_3.setObjectName("QLabel_Sortie_3")
        self.QFrame_ExS = QtWidgets.QFrame(self.centralwidget)
        self.QFrame_ExS.setGeometry(QtCore.QRect(29, 400, 331, 181))
        self.QFrame_ExS.setStyleSheet("background-color: rgb(28, 38, 61);")
        self.QFrame_ExS.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.QFrame_ExS.setFrameShadow(QtWidgets.QFrame.Raised)
        self.QFrame_ExS.setObjectName("QFrame_ExS")
        self.QLabel_Entree = QtWidgets.QLabel(self.QFrame_ExS)
        self.QLabel_Entree.setGeometry(QtCore.QRect(0, 0, 161, 41))
        self.QLabel_Entree.setStyleSheet("background-color: rgb(28, 38, 61);\n"
"font: 10pt \"MS Shell Dlg 2\";\n"
"color: rgb(255, 255, 255);\n"
"")
        self.QLabel_Entree.setAlignment(QtCore.Qt.AlignCenter)
        self.QLabel_Entree.setObjectName("QLabel_Entree")
        self.QLabel_Sortie = QtWidgets.QLabel(self.QFrame_ExS)
        self.QLabel_Sortie.setGeometry(QtCore.QRect(170, 0, 161, 41))
        self.QLabel_Sortie.setStyleSheet("background-color: rgb(28, 38, 61);\n"
"font: 10pt \"MS Shell Dlg 2\";\n"
"color: rgb(255, 255, 255);\n"
"")
        self.QLabel_Sortie.setAlignment(QtCore.Qt.AlignCenter)
        self.QLabel_Sortie.setObjectName("QLabel_Sortie")
        self.QTextEdit_Entree = QtWidgets.QTextEdit(self.QFrame_ExS)
        self.QTextEdit_Entree.setGeometry(QtCore.QRect(0, 40, 161, 141))
        self.QTextEdit_Entree.setStyleSheet("background-color: rgb(28, 38, 61);\n"
"font: 6pt \"MS Shell Dlg 2\";\n"
"color: rgb(255, 255, 255);\n"
"")
        self.QTextEdit_Entree.setObjectName("QTextEdit_Entree")
        self.QTextEdit_Sortie = QtWidgets.QTextEdit(self.QFrame_ExS)
        self.QTextEdit_Sortie.setGeometry(QtCore.QRect(170, 40, 161, 141))
        self.QTextEdit_Sortie.setStyleSheet("background-color: rgb(28, 38, 61);\n"
"font: 6pt \"MS Shell Dlg 2\";\n"
"color: rgb(255, 255, 255);\n"
"")
        self.QTextEdit_Sortie.setObjectName("QTextEdit_Sortie")
        self.QFrame_Clavier = QtWidgets.QFrame(self.centralwidget)
        self.QFrame_Clavier.setGeometry(QtCore.QRect(390, 359, 801, 221))
        self.QFrame_Clavier.setStyleSheet("background-color: rgb(28, 38, 61);\n"
"font: 7pt \"MS Shell Dlg 2\";\n"
"color: rgb(255, 255, 255);\n"
"")
        self.QFrame_Clavier.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.QFrame_Clavier.setFrameShadow(QtWidgets.QFrame.Raised)
        self.QFrame_Clavier.setObjectName("QFrame_Clavier")
        self.Pbtn_Q = QtWidgets.QPushButton(self.QFrame_Clavier)
        self.Pbtn_Q.setGeometry(QtCore.QRect(0, 20, 75, 51))
        self.Pbtn_Q.setStyleSheet("QPushButton{\n"
"border: 3px solid rgb(28, 38, 61);\n"
"color: black;\n"
"background-color: white;\n"
"border-radius: 20px;\n"
"}\n"
"\n"
"QPushButton:Hover{\n"
"border: 3px solid white;\n"
"color: white;\n"
"background-color:  rgb(28, 38, 61);\n"
"border-radius: 20px;\n"
"}")
        self.Pbtn_Q.setObjectName("Pbtn_Q")
        self.Pbtn_W = QtWidgets.QPushButton(self.QFrame_Clavier)
        self.Pbtn_W.setGeometry(QtCore.QRect(90, 20, 75, 51))
        self.Pbtn_W.setStyleSheet("QPushButton{\n"
"border: 3px solid rgb(28, 38, 61);\n"
"color: black;\n"
"background-color: white;\n"
"border-radius: 20px;\n"
"}\n"
"\n"
"QPushButton:Hover{\n"
"border: 3px solid white;\n"
"color: white;\n"
"background-color:  rgb(28, 38, 61);\n"
"border-radius: 20px;\n"
"}")
        self.Pbtn_W.setObjectName("Pbtn_W")
        self.Pbtn_E = QtWidgets.QPushButton(self.QFrame_Clavier)
        self.Pbtn_E.setGeometry(QtCore.QRect(180, 20, 75, 51))
        self.Pbtn_E.setStyleSheet("QPushButton{\n"
"border: 3px solid rgb(28, 38, 61);\n"
"color: black;\n"
"background-color: white;\n"
"border-radius: 20px;\n"
"}\n"
"\n"
"QPushButton:Hover{\n"
"border: 3px solid white;\n"
"color: white;\n"
"background-color:  rgb(28, 38, 61);\n"
"border-radius: 20px;\n"
"}")
        self.Pbtn_E.setObjectName("Pbtn_E")
        self.Pbtn_R = QtWidgets.QPushButton(self.QFrame_Clavier)
        self.Pbtn_R.setGeometry(QtCore.QRect(270, 20, 75, 51))
        self.Pbtn_R.setStyleSheet("QPushButton{\n"
"border: 3px solid rgb(28, 38, 61);\n"
"color: black;\n"
"background-color: white;\n"
"border-radius: 20px;\n"
"}\n"
"\n"
"QPushButton:Hover{\n"
"border: 3px solid white;\n"
"color: white;\n"
"background-color:  rgb(28, 38, 61);\n"
"border-radius: 20px;\n"
"}")
        self.Pbtn_R.setObjectName("Pbtn_R")
        self.Pbtn_T = QtWidgets.QPushButton(self.QFrame_Clavier)
        self.Pbtn_T.setGeometry(QtCore.QRect(360, 20, 75, 51))
        self.Pbtn_T.setStyleSheet("QPushButton{\n"
"border: 3px solid rgb(28, 38, 61);\n"
"color: black;\n"
"background-color: white;\n"
"border-radius: 20px;\n"
"}\n"
"\n"
"QPushButton:Hover{\n"
"border: 3px solid white;\n"
"color: white;\n"
"background-color:  rgb(28, 38, 61);\n"
"border-radius: 20px;\n"
"}")
        self.Pbtn_T.setObjectName("Pbtn_T")
        self.Pbtn_U = QtWidgets.QPushButton(self.QFrame_Clavier)
        self.Pbtn_U.setGeometry(QtCore.QRect(540, 20, 75, 51))
        self.Pbtn_U.setStyleSheet("QPushButton{\n"
"border: 3px solid rgb(28, 38, 61);\n"
"color: black;\n"
"background-color: white;\n"
"border-radius: 20px;\n"
"}\n"
"\n"
"QPushButton:Hover{\n"
"border: 3px solid white;\n"
"color: white;\n"
"background-color:  rgb(28, 38, 61);\n"
"border-radius: 20px;\n"
"}")
        self.Pbtn_U.setObjectName("Pbtn_U")
        self.Pbtn_Z = QtWidgets.QPushButton(self.QFrame_Clavier)
        self.Pbtn_Z.setGeometry(QtCore.QRect(450, 20, 75, 51))
        self.Pbtn_Z.setStyleSheet("QPushButton{\n"
"border: 3px solid rgb(28, 38, 61);\n"
"color: black;\n"
"background-color: white;\n"
"border-radius: 20px;\n"
"}\n"
"\n"
"QPushButton:Hover{\n"
"border: 3px solid white;\n"
"color: white;\n"
"background-color:  rgb(28, 38, 61);\n"
"border-radius: 20px;\n"
"}")
        self.Pbtn_Z.setObjectName("Pbtn_Z")
        self.Pbtn_I = QtWidgets.QPushButton(self.QFrame_Clavier)
        self.Pbtn_I.setGeometry(QtCore.QRect(630, 20, 75, 51))
        self.Pbtn_I.setStyleSheet("QPushButton{\n"
"border: 3px solid rgb(28, 38, 61);\n"
"color: black;\n"
"background-color: white;\n"
"border-radius: 20px;\n"
"}\n"
"\n"
"QPushButton:Hover{\n"
"border: 3px solid white;\n"
"color: white;\n"
"background-color:  rgb(28, 38, 61);\n"
"border-radius: 20px;\n"
"}")
        self.Pbtn_I.setObjectName("Pbtn_I")
        self.Pbtn_O = QtWidgets.QPushButton(self.QFrame_Clavier)
        self.Pbtn_O.setGeometry(QtCore.QRect(720, 20, 75, 51))
        self.Pbtn_O.setStyleSheet("QPushButton{\n"
"border: 3px solid rgb(28, 38, 61);\n"
"color: black;\n"
"background-color: white;\n"
"border-radius: 20px;\n"
"}\n"
"\n"
"QPushButton:Hover{\n"
"border: 3px solid white;\n"
"color: white;\n"
"background-color:  rgb(28, 38, 61);\n"
"border-radius: 20px;\n"
"}")
        self.Pbtn_O.setObjectName("Pbtn_O")
        self.Pbtn_P = QtWidgets.QPushButton(self.QFrame_Clavier)
        self.Pbtn_P.setGeometry(QtCore.QRect(0, 160, 75, 51))
        self.Pbtn_P.setStyleSheet("QPushButton{\n"
"border: 3px solid rgb(28, 38, 61);\n"
"color: black;\n"
"background-color: white;\n"
"border-radius: 20px;\n"
"}\n"
"\n"
"QPushButton:Hover{\n"
"border: 3px solid white;\n"
"color: white;\n"
"background-color:  rgb(28, 38, 61);\n"
"border-radius: 20px;\n"
"}")
        self.Pbtn_P.setObjectName("Pbtn_P")
        self.Pbtn_N = QtWidgets.QPushButton(self.QFrame_Clavier)
        self.Pbtn_N.setGeometry(QtCore.QRect(540, 160, 75, 51))
        self.Pbtn_N.setStyleSheet("QPushButton{\n"
"border: 3px solid rgb(28, 38, 61);\n"
"color: black;\n"
"background-color: white;\n"
"border-radius: 20px;\n"
"}\n"
"\n"
"QPushButton:Hover{\n"
"border: 3px solid white;\n"
"color: white;\n"
"background-color:  rgb(28, 38, 61);\n"
"border-radius: 20px;\n"
"}")
        self.Pbtn_N.setObjectName("Pbtn_N")
        self.Pbtn_V = QtWidgets.QPushButton(self.QFrame_Clavier)
        self.Pbtn_V.setGeometry(QtCore.QRect(360, 160, 75, 51))
        self.Pbtn_V.setStyleSheet("QPushButton{\n"
"border: 3px solid rgb(28, 38, 61);\n"
"color: black;\n"
"background-color: white;\n"
"border-radius: 20px;\n"
"}\n"
"\n"
"QPushButton:Hover{\n"
"border: 3px solid white;\n"
"color: white;\n"
"background-color:  rgb(28, 38, 61);\n"
"border-radius: 20px;\n"
"}")
        self.Pbtn_V.setObjectName("Pbtn_V")
        self.Pbtn_X = QtWidgets.QPushButton(self.QFrame_Clavier)
        self.Pbtn_X.setGeometry(QtCore.QRect(180, 160, 75, 51))
        self.Pbtn_X.setStyleSheet("QPushButton{\n"
"border: 3px solid rgb(28, 38, 61);\n"
"color: black;\n"
"background-color: white;\n"
"border-radius: 20px;\n"
"}\n"
"\n"
"QPushButton:Hover{\n"
"border: 3px solid white;\n"
"color: white;\n"
"background-color:  rgb(28, 38, 61);\n"
"border-radius: 20px;\n"
"}")
        self.Pbtn_X.setObjectName("Pbtn_X")
        self.Pbtn_B = QtWidgets.QPushButton(self.QFrame_Clavier)
        self.Pbtn_B.setGeometry(QtCore.QRect(450, 160, 75, 51))
        self.Pbtn_B.setStyleSheet("QPushButton{\n"
"border: 3px solid rgb(28, 38, 61);\n"
"color: black;\n"
"background-color: white;\n"
"border-radius: 20px;\n"
"}\n"
"\n"
"QPushButton:Hover{\n"
"border: 3px solid white;\n"
"color: white;\n"
"background-color:  rgb(28, 38, 61);\n"
"border-radius: 20px;\n"
"}")
        self.Pbtn_B.setObjectName("Pbtn_B")
        self.Pbtn_M = QtWidgets.QPushButton(self.QFrame_Clavier)
        self.Pbtn_M.setGeometry(QtCore.QRect(630, 160, 75, 51))
        self.Pbtn_M.setStyleSheet("QPushButton{\n"
"border: 3px solid rgb(28, 38, 61);\n"
"color: black;\n"
"background-color: white;\n"
"border-radius: 20px;\n"
"}\n"
"\n"
"QPushButton:Hover{\n"
"border: 3px solid white;\n"
"color: white;\n"
"background-color:  rgb(28, 38, 61);\n"
"border-radius: 20px;\n"
"}")
        self.Pbtn_M.setObjectName("Pbtn_M")
        self.Pbtn_Y = QtWidgets.QPushButton(self.QFrame_Clavier)
        self.Pbtn_Y.setGeometry(QtCore.QRect(90, 160, 75, 51))
        self.Pbtn_Y.setStyleSheet("QPushButton{\n"
"border: 3px solid rgb(28, 38, 61);\n"
"color: black;\n"
"background-color: white;\n"
"border-radius: 20px;\n"
"}\n"
"\n"
"QPushButton:Hover{\n"
"border: 3px solid white;\n"
"color: white;\n"
"background-color:  rgb(28, 38, 61);\n"
"border-radius: 20px;\n"
"}")
        self.Pbtn_Y.setObjectName("Pbtn_Y")
        self.Pbtn_C = QtWidgets.QPushButton(self.QFrame_Clavier)
        self.Pbtn_C.setGeometry(QtCore.QRect(270, 160, 75, 51))
        self.Pbtn_C.setStyleSheet("QPushButton{\n"
"border: 3px solid rgb(28, 38, 61);\n"
"color: black;\n"
"background-color: white;\n"
"border-radius: 20px;\n"
"}\n"
"\n"
"QPushButton:Hover{\n"
"border: 3px solid white;\n"
"color: white;\n"
"background-color:  rgb(28, 38, 61);\n"
"border-radius: 20px;\n"
"}")
        self.Pbtn_C.setObjectName("Pbtn_C")
        self.Pbtn_L = QtWidgets.QPushButton(self.QFrame_Clavier)
        self.Pbtn_L.setGeometry(QtCore.QRect(720, 160, 75, 51))
        self.Pbtn_L.setStyleSheet("QPushButton{\n"
"border: 3px solid rgb(28, 38, 61);\n"
"color: black;\n"
"background-color: white;\n"
"border-radius: 20px;\n"
"}\n"
"\n"
"QPushButton:Hover{\n"
"border: 3px solid white;\n"
"color: white;\n"
"background-color:  rgb(28, 38, 61);\n"
"border-radius: 20px;\n"
"}")
        self.Pbtn_L.setObjectName("Pbtn_L")
        self.Pbtn_A = QtWidgets.QPushButton(self.QFrame_Clavier)
        self.Pbtn_A.setGeometry(QtCore.QRect(50, 90, 75, 51))
        self.Pbtn_A.setStyleSheet("QPushButton{\n"
"border: 3px solid rgb(28, 38, 61);\n"
"color: black;\n"
"background-color: white;\n"
"border-radius: 20px;\n"
"}\n"
"\n"
"QPushButton:Hover{\n"
"border: 3px solid white;\n"
"color: white;\n"
"background-color:  rgb(28, 38, 61);\n"
"border-radius: 20px;\n"
"}")
        self.Pbtn_A.setObjectName("Pbtn_A")
        self.Pbtn_D = QtWidgets.QPushButton(self.QFrame_Clavier)
        self.Pbtn_D.setGeometry(QtCore.QRect(230, 90, 75, 51))
        self.Pbtn_D.setStyleSheet("QPushButton{\n"
"border: 3px solid rgb(28, 38, 61);\n"
"color: black;\n"
"background-color: white;\n"
"border-radius: 20px;\n"
"}\n"
"\n"
"QPushButton:Hover{\n"
"border: 3px solid white;\n"
"color: white;\n"
"background-color:  rgb(28, 38, 61);\n"
"border-radius: 20px;\n"
"}")
        self.Pbtn_D.setObjectName("Pbtn_D")
        self.Pbtn_S = QtWidgets.QPushButton(self.QFrame_Clavier)
        self.Pbtn_S.setGeometry(QtCore.QRect(140, 90, 75, 51))
        self.Pbtn_S.setStyleSheet("QPushButton{\n"
"border: 3px solid rgb(28, 38, 61);\n"
"color: black;\n"
"background-color: white;\n"
"border-radius: 20px;\n"
"}\n"
"\n"
"QPushButton:Hover{\n"
"border: 3px solid white;\n"
"color: white;\n"
"background-color:  rgb(28, 38, 61);\n"
"border-radius: 20px;\n"
"}")
        self.Pbtn_S.setObjectName("Pbtn_S")
        self.Pbtn_J = QtWidgets.QPushButton(self.QFrame_Clavier)
        self.Pbtn_J.setGeometry(QtCore.QRect(590, 90, 75, 51))
        self.Pbtn_J.setStyleSheet("QPushButton{\n"
"border: 3px solid rgb(28, 38, 61);\n"
"color: black;\n"
"background-color: white;\n"
"border-radius: 20px;\n"
"}\n"
"\n"
"QPushButton:Hover{\n"
"border: 3px solid white;\n"
"color: white;\n"
"background-color:  rgb(28, 38, 61);\n"
"border-radius: 20px;\n"
"}")
        self.Pbtn_J.setObjectName("Pbtn_J")
        self.Pbtn_K = QtWidgets.QPushButton(self.QFrame_Clavier)
        self.Pbtn_K.setGeometry(QtCore.QRect(680, 90, 75, 51))
        self.Pbtn_K.setStyleSheet("QPushButton{\n"
"border: 3px solid rgb(28, 38, 61);\n"
"color: black;\n"
"background-color: white;\n"
"border-radius: 20px;\n"
"}\n"
"\n"
"QPushButton:Hover{\n"
"border: 3px solid white;\n"
"color: white;\n"
"background-color:  rgb(28, 38, 61);\n"
"border-radius: 20px;\n"
"}")
        self.Pbtn_K.setObjectName("Pbtn_K")
        self.Pbtn_H = QtWidgets.QPushButton(self.QFrame_Clavier)
        self.Pbtn_H.setGeometry(QtCore.QRect(500, 90, 75, 51))
        self.Pbtn_H.setStyleSheet("QPushButton{\n"
"border: 3px solid rgb(28, 38, 61);\n"
"color: black;\n"
"background-color: white;\n"
"border-radius: 20px;\n"
"}\n"
"\n"
"QPushButton:Hover{\n"
"border: 3px solid white;\n"
"color: white;\n"
"background-color:  rgb(28, 38, 61);\n"
"border-radius: 20px;\n"
"}")
        self.Pbtn_H.setObjectName("Pbtn_H")
        self.Pbtn_F = QtWidgets.QPushButton(self.QFrame_Clavier)
        self.Pbtn_F.setGeometry(QtCore.QRect(320, 90, 75, 51))
        self.Pbtn_F.setStyleSheet("QPushButton{\n"
"border: 3px solid rgb(28, 38, 61);\n"
"color: black;\n"
"background-color: white;\n"
"border-radius: 20px;\n"
"}\n"
"\n"
"QPushButton:Hover{\n"
"border: 3px solid white;\n"
"color: white;\n"
"background-color:  rgb(28, 38, 61);\n"
"border-radius: 20px;\n"
"}")
        self.Pbtn_F.setObjectName("Pbtn_F")
        self.Pbtn_G = QtWidgets.QPushButton(self.QFrame_Clavier)
        self.Pbtn_G.setGeometry(QtCore.QRect(410, 90, 75, 51))
        self.Pbtn_G.setStyleSheet("QPushButton{\n"
"border: 3px solid rgb(28, 38, 61);\n"
"color: black;\n"
"background-color: white;\n"
"border-radius: 20px;\n"
"}\n"
"\n"
"QPushButton:Hover{\n"
"border: 3px solid white;\n"
"color: white;\n"
"background-color:  rgb(28, 38, 61);\n"
"border-radius: 20px;\n"
"}")
        self.Pbtn_G.setObjectName("Pbtn_G")
        self.QFrame_Callume = QtWidgets.QFrame(self.centralwidget)
        self.QFrame_Callume.setGeometry(QtCore.QRect(390, 180, 801, 161))
        self.QFrame_Callume.setStyleSheet("background-color: rgb(28, 38, 61);\n"
"font: 7pt \"MS Shell Dlg 2\";\n"
"color: rgb(255, 255, 255);\n"
"")
        self.QFrame_Callume.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.QFrame_Callume.setFrameShadow(QtWidgets.QFrame.Raised)
        self.QFrame_Callume.setObjectName("QFrame_Callume")
        self.label_Q = QtWidgets.QLabel(self.QFrame_Callume)
        self.label_Q.setGeometry(QtCore.QRect(10, 20, 61, 31))
        self.label_Q.setStyleSheet("background-color: white;\n"
"color: black;\n"
"border-radius: 10px;")
        self.label_Q.setAlignment(QtCore.Qt.AlignCenter)
        self.label_Q.setObjectName("label_Q")
        self.label_A = QtWidgets.QLabel(self.QFrame_Callume)
        self.label_A.setGeometry(QtCore.QRect(60, 70, 61, 31))
        self.label_A.setStyleSheet("background-color: white;\n"
"color: black;\n"
"border-radius: 10px;")
        self.label_A.setAlignment(QtCore.Qt.AlignCenter)
        self.label_A.setObjectName("label_A")
        self.label_P = QtWidgets.QLabel(self.QFrame_Callume)
        self.label_P.setGeometry(QtCore.QRect(10, 120, 61, 31))
        self.label_P.setStyleSheet("background-color: white;\n"
"color: black;\n"
"border-radius: 10px;")
        self.label_P.setAlignment(QtCore.Qt.AlignCenter)
        self.label_P.setObjectName("label_P")
        self.label_S = QtWidgets.QLabel(self.QFrame_Callume)
        self.label_S.setGeometry(QtCore.QRect(150, 70, 61, 31))
        self.label_S.setStyleSheet("background-color: white;\n"
"color: black;\n"
"border-radius: 10px;")
        self.label_S.setAlignment(QtCore.Qt.AlignCenter)
        self.label_S.setObjectName("label_S")
        self.label_W = QtWidgets.QLabel(self.QFrame_Callume)
        self.label_W.setGeometry(QtCore.QRect(100, 20, 61, 31))
        self.label_W.setStyleSheet("background-color: white;\n"
"color: black;\n"
"border-radius: 10px;")
        self.label_W.setAlignment(QtCore.Qt.AlignCenter)
        self.label_W.setObjectName("label_W")
        self.label_Y = QtWidgets.QLabel(self.QFrame_Callume)
        self.label_Y.setGeometry(QtCore.QRect(100, 120, 61, 31))
        self.label_Y.setStyleSheet("background-color: white;\n"
"color: black;\n"
"border-radius: 10px;")
        self.label_Y.setAlignment(QtCore.Qt.AlignCenter)
        self.label_Y.setObjectName("label_Y")
        self.label_D = QtWidgets.QLabel(self.QFrame_Callume)
        self.label_D.setGeometry(QtCore.QRect(240, 70, 61, 31))
        self.label_D.setStyleSheet("background-color: white;\n"
"color: black;\n"
"border-radius: 10px;")
        self.label_D.setAlignment(QtCore.Qt.AlignCenter)
        self.label_D.setObjectName("label_D")
        self.label_E = QtWidgets.QLabel(self.QFrame_Callume)
        self.label_E.setGeometry(QtCore.QRect(190, 20, 61, 31))
        self.label_E.setStyleSheet("background-color: white;\n"
"color: black;\n"
"border-radius: 10px;")
        self.label_E.setAlignment(QtCore.Qt.AlignCenter)
        self.label_E.setObjectName("label_E")
        self.label_R = QtWidgets.QLabel(self.QFrame_Callume)
        self.label_R.setGeometry(QtCore.QRect(280, 20, 61, 31))
        self.label_R.setStyleSheet("background-color: white;\n"
"color: black;\n"
"border-radius: 10px;")
        self.label_R.setAlignment(QtCore.Qt.AlignCenter)
        self.label_R.setObjectName("label_R")
        self.label_F = QtWidgets.QLabel(self.QFrame_Callume)
        self.label_F.setGeometry(QtCore.QRect(330, 70, 61, 31))
        self.label_F.setStyleSheet("background-color: white;\n"
"color: black;\n"
"border-radius: 10px;")
        self.label_F.setAlignment(QtCore.Qt.AlignCenter)
        self.label_F.setObjectName("label_F")
        self.label_C = QtWidgets.QLabel(self.QFrame_Callume)
        self.label_C.setGeometry(QtCore.QRect(280, 120, 61, 31))
        self.label_C.setStyleSheet("background-color: white;\n"
"color: black;\n"
"border-radius: 10px;")
        self.label_C.setAlignment(QtCore.Qt.AlignCenter)
        self.label_C.setObjectName("label_C")
        self.label_X = QtWidgets.QLabel(self.QFrame_Callume)
        self.label_X.setGeometry(QtCore.QRect(190, 120, 61, 31))
        self.label_X.setStyleSheet("background-color: white;\n"
"color: black;\n"
"border-radius: 10px;")
        self.label_X.setAlignment(QtCore.Qt.AlignCenter)
        self.label_X.setObjectName("label_X")
        self.label_G = QtWidgets.QLabel(self.QFrame_Callume)
        self.label_G.setGeometry(QtCore.QRect(420, 70, 61, 31))
        self.label_G.setStyleSheet("background-color: white;\n"
"color: black;\n"
"border-radius: 10px;")
        self.label_G.setAlignment(QtCore.Qt.AlignCenter)
        self.label_G.setObjectName("label_G")
        self.label_V = QtWidgets.QLabel(self.QFrame_Callume)
        self.label_V.setGeometry(QtCore.QRect(370, 120, 61, 31))
        self.label_V.setStyleSheet("background-color: white;\n"
"color: black;\n"
"border-radius: 10px;")
        self.label_V.setAlignment(QtCore.Qt.AlignCenter)
        self.label_V.setObjectName("label_V")
        self.label_B = QtWidgets.QLabel(self.QFrame_Callume)
        self.label_B.setGeometry(QtCore.QRect(460, 120, 61, 31))
        self.label_B.setStyleSheet("background-color: white;\n"
"color: black;\n"
"border-radius: 10px;")
        self.label_B.setAlignment(QtCore.Qt.AlignCenter)
        self.label_B.setObjectName("label_B")
        self.label_Z = QtWidgets.QLabel(self.QFrame_Callume)
        self.label_Z.setGeometry(QtCore.QRect(460, 20, 61, 31))
        self.label_Z.setStyleSheet("background-color: white;\n"
"color: black;\n"
"border-radius: 10px;")
        self.label_Z.setAlignment(QtCore.Qt.AlignCenter)
        self.label_Z.setObjectName("label_Z")
        self.label_T = QtWidgets.QLabel(self.QFrame_Callume)
        self.label_T.setGeometry(QtCore.QRect(370, 20, 61, 31))
        self.label_T.setStyleSheet("background-color: white;\n"
"color: black;\n"
"border-radius: 10px;")
        self.label_T.setAlignment(QtCore.Qt.AlignCenter)
        self.label_T.setObjectName("label_T")
        self.label_H = QtWidgets.QLabel(self.QFrame_Callume)
        self.label_H.setGeometry(QtCore.QRect(510, 70, 61, 31))
        self.label_H.setStyleSheet("background-color: white;\n"
"color: black;\n"
"border-radius: 10px;")
        self.label_H.setAlignment(QtCore.Qt.AlignCenter)
        self.label_H.setObjectName("label_H")
        self.label_N = QtWidgets.QLabel(self.QFrame_Callume)
        self.label_N.setGeometry(QtCore.QRect(550, 120, 61, 31))
        self.label_N.setStyleSheet("background-color: white;\n"
"color: black;\n"
"border-radius: 10px;")
        self.label_N.setAlignment(QtCore.Qt.AlignCenter)
        self.label_N.setObjectName("label_N")
        self.label_J = QtWidgets.QLabel(self.QFrame_Callume)
        self.label_J.setGeometry(QtCore.QRect(600, 70, 61, 31))
        self.label_J.setStyleSheet("background-color: white;\n"
"color: black;\n"
"border-radius: 10px;")
        self.label_J.setAlignment(QtCore.Qt.AlignCenter)
        self.label_J.setObjectName("label_J")
        self.label_U = QtWidgets.QLabel(self.QFrame_Callume)
        self.label_U.setGeometry(QtCore.QRect(550, 20, 61, 31))
        self.label_U.setStyleSheet("background-color: white;\n"
"color: black;\n"
"border-radius: 10px;")
        self.label_U.setAlignment(QtCore.Qt.AlignCenter)
        self.label_U.setObjectName("label_U")
        self.label_M = QtWidgets.QLabel(self.QFrame_Callume)
        self.label_M.setGeometry(QtCore.QRect(640, 120, 61, 31))
        self.label_M.setStyleSheet("background-color: white;\n"
"color: black;\n"
"border-radius: 10px;")
        self.label_M.setAlignment(QtCore.Qt.AlignCenter)
        self.label_M.setObjectName("label_M")
        self.label_K = QtWidgets.QLabel(self.QFrame_Callume)
        self.label_K.setGeometry(QtCore.QRect(690, 70, 61, 31))
        self.label_K.setStyleSheet("background-color: white;\n"
"color: black;\n"
"border-radius: 10px;")
        self.label_K.setAlignment(QtCore.Qt.AlignCenter)
        self.label_K.setObjectName("label_K")
        self.label_I = QtWidgets.QLabel(self.QFrame_Callume)
        self.label_I.setGeometry(QtCore.QRect(640, 20, 61, 31))
        self.label_I.setStyleSheet("background-color: white;\n"
"color: black;\n"
"border-radius: 10px;")
        self.label_I.setAlignment(QtCore.Qt.AlignCenter)
        self.label_I.setObjectName("label_I")
        self.label_O = QtWidgets.QLabel(self.QFrame_Callume)
        self.label_O.setGeometry(QtCore.QRect(730, 20, 61, 31))
        self.label_O.setStyleSheet("background-color: white;\n"
"color: black;\n"
"border-radius: 10px;")
        self.label_O.setAlignment(QtCore.Qt.AlignCenter)
        self.label_O.setObjectName("label_O")
        self.label_L = QtWidgets.QLabel(self.QFrame_Callume)
        self.label_L.setGeometry(QtCore.QRect(730, 120, 61, 31))
        self.label_L.setStyleSheet("background-color: white;\n"
"color: black;\n"
"border-radius: 10px;")
        self.label_L.setAlignment(QtCore.Qt.AlignCenter)
        self.label_L.setObjectName("label_L")
        self.QFrame_Plugs = QtWidgets.QFrame(self.centralwidget)
        self.QFrame_Plugs.setGeometry(QtCore.QRect(390, 10, 801, 161))
        self.QFrame_Plugs.setStyleSheet("background-color: rgb(28, 38, 61);\n"
"font: 7pt \"MS Shell Dlg 2\";\n"
"color: rgb(255, 255, 255);\n"
"")
        self.QFrame_Plugs.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.QFrame_Plugs.setFrameShadow(QtWidgets.QFrame.Raised)
        self.QFrame_Plugs.setObjectName("QFrame_Plugs")
        self.label_27 = QtWidgets.QLabel(self.QFrame_Plugs)
        self.label_27.setGeometry(QtCore.QRect(10, 10, 41, 41))
        self.label_27.setStyleSheet("background-color: white;\n"
"color: black;\n"
"")
        self.label_27.setAlignment(QtCore.Qt.AlignCenter)
        self.label_27.setObjectName("label_27")
        self.label_28 = QtWidgets.QLabel(self.QFrame_Plugs)
        self.label_28.setGeometry(QtCore.QRect(10, 60, 41, 41))
        self.label_28.setStyleSheet("background-color: white;\n"
"color: black;\n"
"")
        self.label_28.setAlignment(QtCore.Qt.AlignCenter)
        self.label_28.setObjectName("label_28")
        self.label_29 = QtWidgets.QLabel(self.QFrame_Plugs)
        self.label_29.setGeometry(QtCore.QRect(10, 110, 41, 41))
        self.label_29.setStyleSheet("background-color: white;\n"
"color: black;\n"
"")
        self.label_29.setAlignment(QtCore.Qt.AlignCenter)
        self.label_29.setObjectName("label_29")
        self.lineEdit_A = QtWidgets.QLineEdit(self.QFrame_Plugs)
        self.lineEdit_A.setGeometry(QtCore.QRect(50, 10, 41, 41))
        self.lineEdit_A.setStyleSheet("background-color: rgb(199, 199, 199);")
        self.lineEdit_A.setObjectName("lineEdit_A")
        self.lineEdit_A.setMaxLength(1)
        self.lineEdit_A.setValidator(QtGui.QRegExpValidator(QtCore.QRegExp("[A-Z]")))
        self.lineEdit_A.setAlignment(QtCore.Qt.AlignCenter)

        self.lineEdit_B = QtWidgets.QLineEdit(self.QFrame_Plugs)
        self.lineEdit_B.setGeometry(QtCore.QRect(50, 60, 41, 41))
        self.lineEdit_B.setStyleSheet("background-color: rgb(199, 199, 199);")
        self.lineEdit_B.setObjectName("lineEdit_B")
        self.lineEdit_C = QtWidgets.QLineEdit(self.QFrame_Plugs)
        self.lineEdit_C.setGeometry(QtCore.QRect(50, 110, 41, 41))
        self.lineEdit_C.setStyleSheet("background-color: rgb(199, 199, 199);")
        self.lineEdit_C.setObjectName("lineEdit_C")
        self.lineEdit_E = QtWidgets.QLineEdit(self.QFrame_Plugs)
        self.lineEdit_E.setGeometry(QtCore.QRect(140, 60, 41, 41))
        self.lineEdit_E.setStyleSheet("background-color: rgb(199, 199, 199);")
        self.lineEdit_E.setObjectName("lineEdit_E")
        self.label_30 = QtWidgets.QLabel(self.QFrame_Plugs)
        self.label_30.setGeometry(QtCore.QRect(100, 10, 41, 41))
        self.label_30.setStyleSheet("background-color: white;\n"
"color: black;\n"
"")
        self.label_30.setAlignment(QtCore.Qt.AlignCenter)
        self.label_30.setObjectName("label_30")
        self.label_31 = QtWidgets.QLabel(self.QFrame_Plugs)
        self.label_31.setGeometry(QtCore.QRect(100, 110, 41, 41))
        self.label_31.setStyleSheet("background-color: white;\n"
"color: black;\n"
"")
        self.label_31.setAlignment(QtCore.Qt.AlignCenter)
        self.label_31.setObjectName("label_31")
        self.lineEdit_F = QtWidgets.QLineEdit(self.QFrame_Plugs)
        self.lineEdit_F.setGeometry(QtCore.QRect(140, 110, 41, 41))
        self.lineEdit_F.setStyleSheet("background-color: rgb(199, 199, 199);")
        self.lineEdit_F.setObjectName("lineEdit_F")
        self.lineEdit_D = QtWidgets.QLineEdit(self.QFrame_Plugs)
        self.lineEdit_D.setGeometry(QtCore.QRect(140, 10, 41, 41))
        self.lineEdit_D.setStyleSheet("background-color: rgb(199, 199, 199);")
        self.lineEdit_D.setObjectName("lineEdit_D")
        self.label_32 = QtWidgets.QLabel(self.QFrame_Plugs)
        self.label_32.setGeometry(QtCore.QRect(100, 60, 41, 41))
        self.label_32.setStyleSheet("background-color: white;\n"
"color: black;\n"
"")
        self.label_32.setAlignment(QtCore.Qt.AlignCenter)
        self.label_32.setObjectName("label_32")
        self.lineEdit_H = QtWidgets.QLineEdit(self.QFrame_Plugs)
        self.lineEdit_H.setGeometry(QtCore.QRect(230, 60, 41, 41))
        self.lineEdit_H.setStyleSheet("background-color: rgb(199, 199, 199);")
        self.lineEdit_H.setObjectName("lineEdit_H")
        self.label_33 = QtWidgets.QLabel(self.QFrame_Plugs)
        self.label_33.setGeometry(QtCore.QRect(190, 10, 41, 41))
        self.label_33.setStyleSheet("background-color: white;\n"
"color: black;\n"
"")
        self.label_33.setAlignment(QtCore.Qt.AlignCenter)
        self.label_33.setObjectName("label_33")
        self.label_34 = QtWidgets.QLabel(self.QFrame_Plugs)
        self.label_34.setGeometry(QtCore.QRect(190, 110, 41, 41))
        self.label_34.setStyleSheet("background-color: white;\n"
"color: black;\n"
"")
        self.label_34.setAlignment(QtCore.Qt.AlignCenter)
        self.label_34.setObjectName("label_34")
        self.label_35 = QtWidgets.QLabel(self.QFrame_Plugs)
        self.label_35.setGeometry(QtCore.QRect(280, 10, 41, 41))
        self.label_35.setStyleSheet("background-color: white;\n"
"color: black;\n"
"")
        self.label_35.setAlignment(QtCore.Qt.AlignCenter)
        self.label_35.setObjectName("label_35")
        self.label_36 = QtWidgets.QLabel(self.QFrame_Plugs)
        self.label_36.setGeometry(QtCore.QRect(280, 60, 41, 41))
        self.label_36.setStyleSheet("background-color: white;\n"
"color: black;\n"
"")
        self.label_36.setAlignment(QtCore.Qt.AlignCenter)
        self.label_36.setObjectName("label_36")
        self.lineEdit_I = QtWidgets.QLineEdit(self.QFrame_Plugs)
        self.lineEdit_I.setGeometry(QtCore.QRect(230, 110, 41, 41))
        self.lineEdit_I.setStyleSheet("background-color: rgb(199, 199, 199);")
        self.lineEdit_I.setObjectName("lineEdit_I")
        self.lineEdit_G = QtWidgets.QLineEdit(self.QFrame_Plugs)
        self.lineEdit_G.setGeometry(QtCore.QRect(230, 10, 41, 41))
        self.lineEdit_G.setStyleSheet("background-color: rgb(199, 199, 199);")
        self.lineEdit_G.setObjectName("lineEdit_G")
        self.label_37 = QtWidgets.QLabel(self.QFrame_Plugs)
        self.label_37.setGeometry(QtCore.QRect(190, 60, 41, 41))
        self.label_37.setStyleSheet("background-color: white;\n"
"color: black;\n"
"")
        self.label_37.setAlignment(QtCore.Qt.AlignCenter)
        self.label_37.setObjectName("label_37")
        self.lineEdit_J = QtWidgets.QLineEdit(self.QFrame_Plugs)
        self.lineEdit_J.setGeometry(QtCore.QRect(320, 10, 41, 41))
        self.lineEdit_J.setStyleSheet("background-color: rgb(199, 199, 199);")
        self.lineEdit_J.setObjectName("lineEdit_J")
        self.lineEdit_K = QtWidgets.QLineEdit(self.QFrame_Plugs)
        self.lineEdit_K.setGeometry(QtCore.QRect(320, 60, 41, 41))
        self.lineEdit_K.setStyleSheet("background-color: rgb(199, 199, 199);")
        self.lineEdit_K.setObjectName("lineEdit_K")
        self.label_38 = QtWidgets.QLabel(self.QFrame_Plugs)
        self.label_38.setGeometry(QtCore.QRect(280, 110, 41, 41))
        self.label_38.setStyleSheet("background-color: white;\n"
"color: black;\n"
"")
        self.label_38.setAlignment(QtCore.Qt.AlignCenter)
        self.label_38.setObjectName("label_38")
        self.lineEdit_L = QtWidgets.QLineEdit(self.QFrame_Plugs)
        self.lineEdit_L.setGeometry(QtCore.QRect(320, 110, 41, 41))
        self.lineEdit_L.setStyleSheet("background-color: rgb(199, 199, 199);")
        self.lineEdit_L.setObjectName("lineEdit_L")
        self.lineEdit_Q = QtWidgets.QLineEdit(self.QFrame_Plugs)
        self.lineEdit_Q.setGeometry(QtCore.QRect(500, 60, 41, 41))
        self.lineEdit_Q.setStyleSheet("background-color: rgb(199, 199, 199);")
        self.lineEdit_Q.setObjectName("lineEdit_Q")
        self.lineEdit_U = QtWidgets.QLineEdit(self.QFrame_Plugs)
        self.lineEdit_U.setGeometry(QtCore.QRect(680, 10, 41, 41))
        self.lineEdit_U.setStyleSheet("background-color: rgb(199, 199, 199);")
        self.lineEdit_U.setObjectName("lineEdit_U")
        self.lineEdit_V = QtWidgets.QLineEdit(self.QFrame_Plugs)
        self.lineEdit_V.setGeometry(QtCore.QRect(680, 60, 41, 41))
        self.lineEdit_V.setStyleSheet("background-color: rgb(199, 199, 199);")
        self.lineEdit_V.setObjectName("lineEdit_V")
        self.lineEdit_M = QtWidgets.QLineEdit(self.QFrame_Plugs)
        self.lineEdit_M.setGeometry(QtCore.QRect(410, 10, 41, 41))
        self.lineEdit_M.setStyleSheet("background-color: rgb(199, 199, 199);")
        self.lineEdit_M.setObjectName("lineEdit_M")
        self.label_39 = QtWidgets.QLabel(self.QFrame_Plugs)
        self.label_39.setGeometry(QtCore.QRect(640, 60, 41, 41))
        self.label_39.setStyleSheet("background-color: white;\n"
"color: black;\n"
"")
        self.label_39.setAlignment(QtCore.Qt.AlignCenter)
        self.label_39.setObjectName("label_39")
        self.label_40 = QtWidgets.QLabel(self.QFrame_Plugs)
        self.label_40.setGeometry(QtCore.QRect(370, 110, 41, 41))
        self.label_40.setStyleSheet("background-color: white;\n"
"color: black;\n"
"")
        self.label_40.setAlignment(QtCore.Qt.AlignCenter)
        self.label_40.setObjectName("label_40")
        self.label_41 = QtWidgets.QLabel(self.QFrame_Plugs)
        self.label_41.setGeometry(QtCore.QRect(550, 10, 41, 41))
        self.label_41.setStyleSheet("background-color: white;\n"
"color: black;\n"
"")
        self.label_41.setAlignment(QtCore.Qt.AlignCenter)
        self.label_41.setObjectName("label_41")
        self.lineEdit_W = QtWidgets.QLineEdit(self.QFrame_Plugs)
        self.lineEdit_W.setGeometry(QtCore.QRect(680, 110, 41, 41))
        self.lineEdit_W.setStyleSheet("background-color: rgb(199, 199, 199);")
        self.lineEdit_W.setObjectName("lineEdit_W")
        self.lineEdit_N = QtWidgets.QLineEdit(self.QFrame_Plugs)
        self.lineEdit_N.setGeometry(QtCore.QRect(410, 60, 41, 41))
        self.lineEdit_N.setStyleSheet("background-color: rgb(199, 199, 199);")
        self.lineEdit_N.setObjectName("lineEdit_N")
        self.label_42 = QtWidgets.QLabel(self.QFrame_Plugs)
        self.label_42.setGeometry(QtCore.QRect(460, 10, 41, 41))
        self.label_42.setStyleSheet("background-color: white;\n"
"color: black;\n"
"")
        self.label_42.setAlignment(QtCore.Qt.AlignCenter)
        self.label_42.setObjectName("label_42")
        self.lineEdit_R = QtWidgets.QLineEdit(self.QFrame_Plugs)
        self.lineEdit_R.setGeometry(QtCore.QRect(500, 110, 41, 41))
        self.lineEdit_R.setStyleSheet("background-color: rgb(199, 199, 199);")
        self.lineEdit_R.setObjectName("lineEdit_R")
        self.label_43 = QtWidgets.QLabel(self.QFrame_Plugs)
        self.label_43.setGeometry(QtCore.QRect(460, 60, 41, 41))
        self.label_43.setStyleSheet("background-color: white;\n"
"color: black;\n"
"")
        self.label_43.setAlignment(QtCore.Qt.AlignCenter)
        self.label_43.setObjectName("label_43")
        self.label_44 = QtWidgets.QLabel(self.QFrame_Plugs)
        self.label_44.setGeometry(QtCore.QRect(370, 10, 41, 41))
        self.label_44.setStyleSheet("background-color: white;\n"
"color: black;\n"
"")
        self.label_44.setAlignment(QtCore.Qt.AlignCenter)
        self.label_44.setObjectName("label_44")
        self.lineEdit_S = QtWidgets.QLineEdit(self.QFrame_Plugs)
        self.lineEdit_S.setGeometry(QtCore.QRect(590, 10, 41, 41))
        self.lineEdit_S.setStyleSheet("background-color: rgb(199, 199, 199);")
        self.lineEdit_S.setObjectName("lineEdit_S")
        self.lineEdit_T = QtWidgets.QLineEdit(self.QFrame_Plugs)
        self.lineEdit_T.setGeometry(QtCore.QRect(590, 60, 41, 41))
        self.lineEdit_T.setStyleSheet("background-color: rgb(199, 199, 199);")
        self.lineEdit_T.setObjectName("lineEdit_T")
        self.label_45 = QtWidgets.QLabel(self.QFrame_Plugs)
        self.label_45.setGeometry(QtCore.QRect(370, 60, 41, 41))
        self.label_45.setStyleSheet("background-color: white;\n"
"color: black;\n"
"")
        self.label_45.setAlignment(QtCore.Qt.AlignCenter)
        self.label_45.setObjectName("label_45")
        self.lineEdit_C = QtWidgets.QLineEdit(self.QFrame_Plugs)
        self.lineEdit_C.setGeometry(QtCore.QRect(590, 110, 41, 41))
        self.lineEdit_C.setStyleSheet("background-color: rgb(199, 199, 199);")
        self.lineEdit_C.setObjectName("lineEdit_C")
        self.label_46 = QtWidgets.QLabel(self.QFrame_Plugs)
        self.label_46.setGeometry(QtCore.QRect(550, 110, 41, 41))
        self.label_46.setStyleSheet("background-color: white;\n"
"color: black;\n"
"")
        self.label_46.setAlignment(QtCore.Qt.AlignCenter)
        self.label_46.setObjectName("label_46")
        self.lineEdit_O = QtWidgets.QLineEdit(self.QFrame_Plugs)
        self.lineEdit_O.setGeometry(QtCore.QRect(410, 110, 41, 41))
        self.lineEdit_O.setStyleSheet("background-color: rgb(199, 199, 199);")
        self.lineEdit_O.setObjectName("lineEdit_O")
        self.lineEdit_P = QtWidgets.QLineEdit(self.QFrame_Plugs)
        self.lineEdit_P.setGeometry(QtCore.QRect(500, 10, 41, 41))
        self.lineEdit_P.setStyleSheet("background-color: rgb(199, 199, 199);")
        self.lineEdit_P.setObjectName("lineEdit_P")
        self.label_47 = QtWidgets.QLabel(self.QFrame_Plugs)
        self.label_47.setGeometry(QtCore.QRect(640, 110, 41, 41))
        self.label_47.setStyleSheet("background-color: white;\n"
"color: black;\n"
"")
        self.label_47.setAlignment(QtCore.Qt.AlignCenter)
        self.label_47.setObjectName("label_47")
        self.label_48 = QtWidgets.QLabel(self.QFrame_Plugs)
        self.label_48.setGeometry(QtCore.QRect(550, 60, 41, 41))
        self.label_48.setStyleSheet("background-color: white;\n"
"color: black;\n"
"")
        self.label_48.setAlignment(QtCore.Qt.AlignCenter)
        self.label_48.setObjectName("label_48")
        self.label_49 = QtWidgets.QLabel(self.QFrame_Plugs)
        self.label_49.setGeometry(QtCore.QRect(460, 110, 41, 41))
        self.label_49.setStyleSheet("background-color: white;\n"
"color: black;\n"
"")
        self.label_49.setAlignment(QtCore.Qt.AlignCenter)
        self.label_49.setObjectName("label_49")
        self.label_50 = QtWidgets.QLabel(self.QFrame_Plugs)
        self.label_50.setGeometry(QtCore.QRect(640, 10, 41, 41))
        self.label_50.setStyleSheet("background-color: white;\n"
"color: black;\n"
"")
        self.label_50.setAlignment(QtCore.Qt.AlignCenter)
        self.label_50.setObjectName("label_50")
        self.label_51 = QtWidgets.QLabel(self.QFrame_Plugs)
        self.label_51.setGeometry(QtCore.QRect(740, 10, 51, 31))
        self.label_51.setStyleSheet("background-color: white;\n"
"color: black;\n"
"")
        self.label_51.setAlignment(QtCore.Qt.AlignCenter)
        self.label_51.setObjectName("label_51")
        self.lineEdit_Y = QtWidgets.QLineEdit(self.QFrame_Plugs)
        self.lineEdit_Y.setGeometry(QtCore.QRect(740, 40, 51, 31))
        self.lineEdit_Y.setStyleSheet("background-color: rgb(199, 199, 199);")
        self.lineEdit_Y.setObjectName("lineEdit_Y")
        self.lineEdit_Z = QtWidgets.QLineEdit(self.QFrame_Plugs)
        self.lineEdit_Z.setGeometry(QtCore.QRect(740, 120, 51, 31))
        self.lineEdit_Z.setStyleSheet("background-color: rgb(199, 199, 199);")
        self.lineEdit_Z.setText("")
        self.lineEdit_Z.setObjectName("lineEdit_Z")
        self.label_52 = QtWidgets.QLabel(self.QFrame_Plugs)
        self.label_52.setGeometry(QtCore.QRect(740, 90, 51, 31))
        self.label_52.setStyleSheet("background-color: white;\n"
"color: black;\n"
"")
        self.label_52.setAlignment(QtCore.Qt.AlignCenter)
        self.label_52.setObjectName("label_52")
        MainWindow.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.pushButton.setText(_translate("MainWindow", "Comment utiliser ?"))
        self.pushButton_2.setText(_translate("MainWindow", "Facts sur Enigma"))
        self.label_53.setText(_translate("MainWindow", "1"))
        self.label_54.setText(_translate("MainWindow", "2"))
        self.label_55.setText(_translate("MainWindow", "3"))
        self.pushButton_3.setText(_translate("MainWindow", "Change"))
        self.pushButton_4.setText(_translate("MainWindow", "Change"))
        self.pushButton_5.setText(_translate("MainWindow", "Change"))
        self.pushButton_6.setText(_translate("MainWindow", "Change"))
        self.label_57.setText(_translate("MainWindow", "UKW-B"))
        self.QLabel_Sortie_2.setText(_translate("MainWindow", "Reflecteurs"))
        self.QLabel_Sortie_3.setText(_translate("MainWindow", "Rotors"))
        self.QLabel_Entree.setText(_translate("MainWindow", "Entrée :"))
        self.QLabel_Sortie.setText(_translate("MainWindow", "Sortie :"))
        self.Pbtn_Q.setText(_translate("MainWindow", "Q"))
        self.Pbtn_W.setText(_translate("MainWindow", "W"))
        self.Pbtn_E.setText(_translate("MainWindow", "E"))
        self.Pbtn_R.setText(_translate("MainWindow", "R"))
        self.Pbtn_T.setText(_translate("MainWindow", "T"))
        self.Pbtn_U.setText(_translate("MainWindow", "U"))
        self.Pbtn_Z.setText(_translate("MainWindow", "Z"))
        self.Pbtn_I.setText(_translate("MainWindow", "I"))
        self.Pbtn_O.setText(_translate("MainWindow", "O"))
        self.Pbtn_P.setText(_translate("MainWindow", "P"))
        self.Pbtn_N.setText(_translate("MainWindow", "N"))
        self.Pbtn_V.setText(_translate("MainWindow", "V"))
        self.Pbtn_X.setText(_translate("MainWindow", "X"))
        self.Pbtn_B.setText(_translate("MainWindow", "B"))
        self.Pbtn_M.setText(_translate("MainWindow", "M"))
        self.Pbtn_Y.setText(_translate("MainWindow", "Y"))
        self.Pbtn_C.setText(_translate("MainWindow", "C"))
        self.Pbtn_L.setText(_translate("MainWindow", "L"))
        self.Pbtn_A.setText(_translate("MainWindow", "A"))
        self.Pbtn_D.setText(_translate("MainWindow", "D"))
        self.Pbtn_S.setText(_translate("MainWindow", "S"))
        self.Pbtn_J.setText(_translate("MainWindow", "J"))
        self.Pbtn_K.setText(_translate("MainWindow", "K"))
        self.Pbtn_H.setText(_translate("MainWindow", "H"))
        self.Pbtn_F.setText(_translate("MainWindow", "F"))
        self.Pbtn_G.setText(_translate("MainWindow", "G"))
        self.label_Q.setText(_translate("MainWindow", "Q"))
        self.label_A.setText(_translate("MainWindow", "A"))
        self.label_P.setText(_translate("MainWindow", "P"))
        self.label_S.setText(_translate("MainWindow", "S"))
        self.label_W.setText(_translate("MainWindow", "W"))
        self.label_Y.setText(_translate("MainWindow", "Y"))
        self.label_D.setText(_translate("MainWindow", "D"))
        self.label_E.setText(_translate("MainWindow", "E"))
        self.label_R.setText(_translate("MainWindow", "R"))
        self.label_F.setText(_translate("MainWindow", "F"))
        self.label_C.setText(_translate("MainWindow", "C"))
        self.label_X.setText(_translate("MainWindow", "X"))
        self.label_G.setText(_translate("MainWindow", "G"))
        self.label_V.setText(_translate("MainWindow", "V"))
        self.label_B.setText(_translate("MainWindow", "B"))
        self.label_Z.setText(_translate("MainWindow", "Z"))
        self.label_T.setText(_translate("MainWindow", "T"))
        self.label_H.setText(_translate("MainWindow", "H"))
        self.label_N.setText(_translate("MainWindow", "N"))
        self.label_J.setText(_translate("MainWindow", "J"))
        self.label_U.setText(_translate("MainWindow", "U"))
        self.label_M.setText(_translate("MainWindow", "M"))
        self.label_K.setText(_translate("MainWindow", "K"))
        self.label_I.setText(_translate("MainWindow", "I"))
        self.label_O.setText(_translate("MainWindow", "O"))
        self.label_L.setText(_translate("MainWindow", "L"))
        self.label_27.setText(_translate("MainWindow", "A"))
        self.label_28.setText(_translate("MainWindow", "B"))
        self.label_29.setText(_translate("MainWindow", "C"))
        self.label_30.setText(_translate("MainWindow", "D"))
        self.label_31.setText(_translate("MainWindow", "F"))
        self.label_32.setText(_translate("MainWindow", "E"))
        self.label_33.setText(_translate("MainWindow", "G"))
        self.label_34.setText(_translate("MainWindow", "I"))
        self.label_35.setText(_translate("MainWindow", "J"))
        self.label_36.setText(_translate("MainWindow", "K"))
        self.label_37.setText(_translate("MainWindow", "H"))
        self.label_38.setText(_translate("MainWindow", "L"))
        self.label_39.setText(_translate("MainWindow", "V"))
        self.label_40.setText(_translate("MainWindow", "O"))
        self.label_41.setText(_translate("MainWindow", "S"))
        self.label_42.setText(_translate("MainWindow", "P"))
        self.label_43.setText(_translate("MainWindow", "Q"))
        self.label_44.setText(_translate("MainWindow", "M"))
        self.label_45.setText(_translate("MainWindow", "N"))
        self.label_46.setText(_translate("MainWindow", "C"))
        self.label_47.setText(_translate("MainWindow", "W"))
        self.label_48.setText(_translate("MainWindow", "T"))
        self.label_49.setText(_translate("MainWindow", "R"))
        self.label_50.setText(_translate("MainWindow", "U"))
        self.label_51.setText(_translate("MainWindow", "Y"))
        self.label_52.setText(_translate("MainWindow", "Z"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
